### ISSUE TITLE
Summer 2016 Notes and To-do

### ISSUE THREAD

**Issue by FFAxKenny** [scel-hawaii/scel-hawaii.org#23]
Overall the website still needs work. Feel free to comment on this thread and/or make changes to the todo list.

Notes:

1. We're in need of a better website to hand to interested companies, professors or students.
2. The wiki can be a little messy for someone to start off with - we may need to clean up as well, but I think it would still be beneficial to have a website as a starting point. 

Todo:

- [ ] Overhaul the members page - maybe we need to break things into different pages. 
- [ ] Update the bios for members
- [ ] Create a photo gallery and upload some nice pictures!
- [ ] Create and upload posts for the previous presentations
- [ ] Make the 'contact' page a little nicer
